# Generated by Django 6.0.3 on 2026-04-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room'),
        ('chat', '0002_room_alter_message_room'),
    ]

    operations = [
    ]
