# Generated by Django 6.0.3 on 2026-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_merge_0002_room_0002_room_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed')], default='sent', max_length=10),
        ),
    ]
