# Generated by Django 5.0.4 on 2026-04-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_attachment_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice')], default='text', max_length=10),
        ),
    ]
